#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-bayesm
Version  : 3.1.6
Release  : 63
URL      : https://cran.r-project.org/src/contrib/bayesm_3.1-6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bayesm_3.1-6.tar.gz
Summary  : Bayesian Inference for Marketing/Micro-Econometrics
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-bayesm-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-RcppArmadillo
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : R-RcppArmadillo-dev
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
in marketing and micro-econometrics applications.

%package lib
Summary: lib components for the R-bayesm package.
Group: Libraries

%description lib
lib components for the R-bayesm package.


%prep
%setup -q -n bayesm
pushd ..
cp -a bayesm buildavx2
popd
pushd ..
cp -a bayesm buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737135127

%install
export SOURCE_DATE_EPOCH=1737135127
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bayesm/DESCRIPTION
/usr/lib64/R/library/bayesm/INDEX
/usr/lib64/R/library/bayesm/Meta/Rd.rds
/usr/lib64/R/library/bayesm/Meta/data.rds
/usr/lib64/R/library/bayesm/Meta/features.rds
/usr/lib64/R/library/bayesm/Meta/hsearch.rds
/usr/lib64/R/library/bayesm/Meta/links.rds
/usr/lib64/R/library/bayesm/Meta/nsInfo.rds
/usr/lib64/R/library/bayesm/Meta/package.rds
/usr/lib64/R/library/bayesm/Meta/vignette.rds
/usr/lib64/R/library/bayesm/NAMESPACE
/usr/lib64/R/library/bayesm/R/bayesm
/usr/lib64/R/library/bayesm/R/bayesm.rdb
/usr/lib64/R/library/bayesm/R/bayesm.rdx
/usr/lib64/R/library/bayesm/data/Scotch.rda
/usr/lib64/R/library/bayesm/data/bank.rda
/usr/lib64/R/library/bayesm/data/camera.RData
/usr/lib64/R/library/bayesm/data/cheese.rda
/usr/lib64/R/library/bayesm/data/customerSat.rda
/usr/lib64/R/library/bayesm/data/detailing.rda
/usr/lib64/R/library/bayesm/data/margarine.rda
/usr/lib64/R/library/bayesm/data/orangeJuice.rda
/usr/lib64/R/library/bayesm/data/tuna.rda
/usr/lib64/R/library/bayesm/doc/Constrained_MNL_Vignette.R
/usr/lib64/R/library/bayesm/doc/Constrained_MNL_Vignette.Rmd
/usr/lib64/R/library/bayesm/doc/Constrained_MNL_Vignette.html
/usr/lib64/R/library/bayesm/doc/bayesm_Overview_Vignette.R
/usr/lib64/R/library/bayesm/doc/bayesm_Overview_Vignette.Rmd
/usr/lib64/R/library/bayesm/doc/bayesm_Overview_Vignette.html
/usr/lib64/R/library/bayesm/doc/index.html
/usr/lib64/R/library/bayesm/help/AnIndex
/usr/lib64/R/library/bayesm/help/aliases.rds
/usr/lib64/R/library/bayesm/help/bayesm.rdb
/usr/lib64/R/library/bayesm/help/bayesm.rdx
/usr/lib64/R/library/bayesm/help/paths.rds
/usr/lib64/R/library/bayesm/html/00Index.html
/usr/lib64/R/library/bayesm/html/R.css
/usr/lib64/R/library/bayesm/include/bayesm.h

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/bayesm/libs/bayesm.so
/V4/usr/lib64/R/library/bayesm/libs/bayesm.so
/usr/lib64/R/library/bayesm/libs/bayesm.so
